<?php
// $Id$

/**
 * @file
 * Demonstrates use of the Form API.
 *
 * For a full list of elements and attributes, see:
 * http://api.drupal.org/api/drupal/developer--topics--forms_api_reference.html/7
 
 * ADDED This line to demonstrate how to push changees from local deve to Remote repo, and 
 * then pull from remote repo to local production/staging   FTECH & MERGE
 
 
 * Example of PULL
 
 * Third Example
 
 */

/**
 * Implements hook_menu().
 */
function input_menu() {
  $items['input/examples'] = array(
    'title' => 'Form API examples',
    'description' => 'Example of using the Form API.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('input_simple_form'),
    'access callback' => TRUE,
  );
  return $items;
}


/**
 * A simple form.
 */
function input_simple_form($form, &$form_submit) {
  $form['color'] = array(
    '#title' => t('Favorite color'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#description' => t('What is your favorite color? Blue? No, wait-'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  return $form;
}